#! /usr/bin/perl

use strict;
use warnings;
use DirHandle;
use Net::FTP;
use FileHandle;
use DirHandle;
use Cwd qw(chdir);

my $tdir = 'public_html/new/wp-content/themes/twentytwelve-child';

my $ftp = Net::FTP->new("ftp.roystonarchery.org", Debug => 0, Passive => 1)
  or die "cannot get ftp connection\n";

$ftp->login("rhac", 'rhS4ndM4nac!')
  or die "$0 Cannot login: ", $ftp->message;
$ftp->binary();
$ftp->cwd($tdir)
  or die "$0 Cannot cwd: ", $ftp->message;

foreach my $source ('style.css') {
    $ftp->put($source, $source)
          or die "$0 cannot put $source: ", $ftp->message;
}

$ftp->quit;

exit(0);
